#VysteriaLinks created by Intelligence
#Website: https://www.vysteria.org

help:
  - '&b&lCommand List:'
  - ''
  - '&b/discord &8- &7Provides a link to our discord server.'
  - '&b/twitter &8- &7Provides a link to our twitter.'
  - '&b/website &8- &7Provides a link to our website.'