name: VysteriaLinks
main: org.vysteria.links.VysteriaLinks
author: Intelligence
version: 1.0
website: https://www.vysteria.org

commands:
  links:
    description: Main Command
  discord:
    description: Gives you a link to our discord server.
  twitter:
    description: Gives you a link to our twitter.
  website:
    description: Gives then link to our website.